#!/bin/bash
# Recibe 2 parametros

if [ $# -ne 2 ]
then
    echo "CANTIDAD DE PARAMETROS RECIBIDOS INCORRECTA"
fi

echo "Ingrese 2 numeros"
read num1 num2
echo "Suma: $(expr $num1 + $num2)"
echo "Resta: $(expr $num1 - $num2)"
echo "Multiplicacion: $(expr $num1 \* $num2)
if [ $num1 -gt $num2 ]
then
    echo "El mayor es $num1"
else
    echo "El mayor es $num2"
fi
